### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by thomasspiesser** [bigu21/meteor-waypoints#2]
hey,
trying to user your waypoints wrapper. 

i get the above error when i try to use it. 

```
javascript
var waypoint = new Waypoint({
  element: document.getElementById('thing'),
  handler: function(direction) {
    alert('You have scrolled to a thing');
  }
});
```

and the html is 

``` html
<div id="thing"></div>
```

Am I missing something obvious here?
Thanks for your help.

**Comment by gabrielalmeida** [comment]
Hey!

It seems that I've shipped a buggy version on last release. The new version has a hotfix, can you confirm if everything works now?

Update your packages to get the latest version on Atmosphere.

Thanks!

**Comment by denoise** [comment]
Hi,

I was getting the same issue as @thomasspiesser and now the updated version throws a new error:
Uncaught Error: No element option passed to Waypoint constructort @ waypoints.min.js:7

thanks for your help!

**Comment by thomasspiesser** [comment]
``` javascript
element: document.getElementById('thing'),
```

did you try with and without the '#' ?

**Comment by denoise** [comment]
;) yes... I did

**Comment by gabrielalmeida** [comment]
Can you paste here your snippet? Does the element that you're selecting through `document.getElementById` exists in DOM, isn't it returning `undefined`?

**Comment by denoise** [comment]
``` html
<div id="thing"></div>
```

``` javascript
var waypoint = new Waypoint({
  element: document.getElementById('thing'),
  handler: function(direction) {
    alert('You have scrolled to a thing');
  }
})
```

**Comment by gabrielalmeida** [comment]
It should work by doing this, testing locally this works as expected. We are missing something here or there is and edge case. 

Can you confirm if by doing `document.getElementById('thing')` on your console it returns the DOM object instead of `undefined`? 

Can you send a reproduction repo of the problem?

**Comment by gabrielalmeida** [comment]
@thomasspiesser Did you managed to get it to work with the updated version?

**Comment by thomasspiesser** [comment]
no, sorry. throws error on server startup.

``` shell
W20150620-17:31:44.198(2)? (STDERR)           
W20150620-17:31:44.199(2)? (STDERR) /Users/thomas/.meteor/packages/meteor-tool/.1.1.3.1f41bnq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150620-17:31:44.199(2)? (STDERR)                         throw(ex);
W20150620-17:31:44.199(2)? (STDERR)                               ^
W20150620-17:31:44.199(2)? (STDERR) ReferenceError: Waypoint is not defined
W20150620-17:31:44.200(2)? (STDERR)     at app/waypoints-test.js:1:55
W20150620-17:31:44.200(2)? (STDERR)     at app/waypoints-test.js:32:3
W20150620-17:31:44.200(2)? (STDERR)     at /Users/thomas/Web_AppDev/exampleApps/waypoints-test/.meteor/local/build/programs/server/boot.js:222:10
W20150620-17:31:44.200(2)? (STDERR)     at Array.forEach (native)
W20150620-17:31:44.200(2)? (STDERR)     at Function._.each._.forEach (/Users/thomas/.meteor/packages/meteor-tool/.1.1.3.1f41bnq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150620-17:31:44.200(2)? (STDERR)     at /Users/thomas/Web_AppDev/exampleApps/waypoints-test/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

[here](https://github.com/thomasspiesser/meteor-waypoints-test) is the code. 
Meteor 1.1.0.2
packages:
bigu:waypoints   0.0.3  Wrapper for waypoints.js
meteor-platform  1.2.2  Include a standard set of Meteor packages in your app

what am i missing?

**Comment by gabrielalmeida** [comment]
Hello, @thomasspiesser, Waypoint is a client-side only package, you need to execute it on client-side folders or by encapsulating it on `Meteor.isClient`. At you `waypoints-test.js` it should be:

``` javascript
if (Meteor.isClient) {
  var waypoint = new Waypoint({
    element: document.getElementById('test'),
    handler: function(direction) {
      alert('You have scrolled to a thing');
    }
  });
}
```

If you're new to Meteor and don't know about client and server specific directories, take a look at:
http://docs.meteor.com/#/full/structuringyourapp

Tell me if you've managed to get it working!

**Comment by gabrielalmeida** [comment]
@denoise Have you solved your problem?

**Comment by thomasspiesser** [comment]
Sorry my bad, haven't paid attention. Of course, originally I used it in the client folder of my project.
If wrapper in Meteor.isClient, server-error is gone.
Browser console:

``` shell
Uncaught Error: No element option passed to Waypoint constructor
```

**Comment by thomasspiesser** [comment]
updated repo if you wanna have another look.

**Comment by denoise** [comment]
hi @gabrielalmeida 
nope, still the same problem.

thanks

**Comment by gabrielalmeida** [comment]
Hello guys, you're both probably on the same mistake, the element passed **MUST** exist on the DOM at the **moment** of `Waypoint's` instantiation, by saying this I mean: `document.getElementById('thing')` **CAN'T be** `undefined`.

In other words, you have to ensure that `Waypoint` is going to be instantiated only when the DOM element you need is already rendered, @thomasspiesser [repo](https://github.com/thomasspiesser/meteor-waypoints-test) will work by simply encapsulating `Waypoint` on `onRendered` like this:

``` javascript
if (Meteor.isClient) {

  Template.hello.onRendered(function() {

    var waypoint = new Waypoint({
      element: document.getElementById('test'),
      handler: function(direction) {
        alert('You have scrolled to a thing');
      }
    });

  });

}
```

@denoise Ping here if this is not your case!

**Comment by thomasspiesser** [comment]
@gabrielalmeida works like a charm, thank you. you think putting the onRendered() example in the docs might be helpful?

**Comment by gabrielalmeida** [comment]
@thomasspiesser Great! I've added a more detailed basic-usage example, let me know if you think something more should be added.

@denoise Waiting to hear from you if you've managed to solve your issue.

Thanks

**Comment by thomasspiesser** [comment]
@gabrielalmeida looks great. that's all one needs to know i think.
